// src/app/shared/header/header.component.ts
import { RouterLink } from '@angular/router';
import {
  Component,
  ElementRef,
  OnDestroy,
  Renderer2,
  ViewChild,
} from '@angular/core';
import { NgForOf, NgIf, NgOptimizedImage } from '@angular/common';

/* Project */
import { productSymbol } from '@app/helpers';
import { AuthStateProvider } from '@app/providers/auth-state.provider';
import { LocalAuthService } from '@app/services/local-auth.service';
import { TUser } from '@app/types';
import { TooltipComponent } from '../tooltip/tooltip.component';
import { MenusStateProvider } from '@app/providers/menus-state.provider';
import { CartStateProvider } from '@app/providers/cart-state.provider';
import { CurrencyStateProvider } from '@app/providers/currency-state.provider';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [TooltipComponent, NgForOf, RouterLink, NgIf, NgOptimizedImage],
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss',
})
export class HeaderComponent implements OnDestroy {
  categories = [
    'Memoria ram',
    'Procesadores',
    'Tarjetas gráficas',
    'Almacenamiento',
    'Monitores',
    'Periféricos',
    'Software',
    'Otros',
    'Accesorios',
    'Memoria ram',
    'Procesadores',
    'Tarjetas gráficas',
    'Memoria ram',
    'Procesadores',
    'Tarjetas gráficas',
    'Almacenamiento',
    'Monitores',
    'Periféricos',
    'Software',
    'Otros',
    'Accesorios',
    'Memoria ram',
    'Procesadores',
    'Tarjetas gráficas',
  ];

  private readonly outsideListener: () => void;

  currency!: string;
  displayMenu: boolean = false;
  displaySidebarMenu!: boolean;

  user?: TUser | null | undefined;

  @ViewChild('menu') menu!: ElementRef;

  constructor(
    private readonly renderer: Renderer2,
    private readonly menusStateProvider: MenusStateProvider,
    private readonly authStateProvider: AuthStateProvider,
    private readonly cartStateProvider: CartStateProvider,
    private readonly currencyStateProvider: CurrencyStateProvider,
    private readonly localAuthService: LocalAuthService,
  ) {
    this.outsideListener = this.renderer.listen(
      'window',
      'click',
      this.outsideCallback.bind(this),
    );

    this.menusStateProvider.showSidebarMenu$.subscribe((showSidebarMenu) => {
      this.displaySidebarMenu = showSidebarMenu;
    });

    this.currencyStateProvider.selectedCurrency$.subscribe((currency) => {
      this.currency = currency;
    });

    this.authStateProvider.user$.subscribe((user) => {
      this.user = user;
    });
  }

  outsideCallback(e: Event) {
    if (!this.menu.nativeElement.contains(e.target)) {
      this.displayMenu = false;
    }
  }

  openSidebarMenu(event: Event) {
    event.stopPropagation();
    this.menusStateProvider.setSidebarMenu(true);
  }

  closeSidebarMenu() {
    this.menusStateProvider.setSidebarMenu(false);
  }

  toggleMenu() {
    this.displayMenu = !this.displayMenu;
  }

  openCart(event: Event) {
    event.stopPropagation();
    this.menusStateProvider.openLateralCart();
  }

  logout() {
    this.localAuthService.logout();
  }

  login() {
    this.localAuthService.login();
  }

  get cartItemsLength(): number {
    return this.cartStateProvider.cartProducts.length;
  }

  get cartProductsTotal(): number {
    return this.cartStateProvider.cartProductsTotal;
  }

  get initials() {
    if (!this.user) {
      return '';
    }

    if (!this.user.name) {
      return 'U';
    }

    const splitNames = this.user.name.split(' ');
    let initials = '';

    splitNames.forEach((name, index) => {
      if (index <= 1) {
        initials += `${name[0]}`;
      }
    });

    return initials;
  }

  ngOnDestroy() {
    this.outsideListener();
  }

  protected readonly productSymbol = productSymbol;
}



<header class="pt-[5px] border-b">
  <div class="px-4 mx-auto max-w-df">
    <div class="h-16 lg:h-[105px] flex items-center gap-4 justify-between">
      <button id="menu-button" type="button" class="lg:hidden" (click)="openSidebarMenu($event)">
        <img src="/icons/menu.svg" alt="menu" class="size-5" />
      </button>
      <a routerLink="/">
        <img
          src="/images/logo.png"
          alt="logo"
          class="size-16 lg:size-[156px] object-contain"
        />
      </a>
      <div class="relative flex-grow hidden lg:block">
        <input
          type="search"
          class="w-full border border-gray-200 rounded-full h-[46px] pl-[15px] pr-[230px]"
          placeholder="Buscar productos..."
        />
        <div #menu>
          <!--          <div>-->
          <button
            type="button"
            class="absolute inset-y-0 right-[45px] h-full px-4 bg-white border border-gray-200 text-[13px] text-[#777777] flex items-center w-44 justify-between"
            (click)="toggleMenu()"
          >
            <span>CATEGORÍAS</span>
            <img src="/icons/rowd.svg" alt="rowd" class="size-3" />
          </button>

          <div class="absolute right-[45px] px-5 py-2 bg-white border
                            border-gray-200 shadow text-[#777777] text-sm
                            uppercase h-[320px] overflow-y-auto
                            scrollbar-thin scrollbar-thumb-gray-300
                            hover:scrollbar-thumb-gray-500
                            scrollbar-track-gray-100 z-10
                            navbar-categories {{ displayMenu  ? 'show' : 'hide' }}">
            <ul class="space-y-2 [&>*>a:hover]:text-primary-600">
              <li *ngFor="let category of categories;">
                <a>{{ category }}</a>
              </li>
            </ul>
          </div>
          <!--          </div>-->
          <div class="absolute inset-y-0 right-0 w-[50px] flex items-center justify-center">
            <img src="/icons/search.svg" alt="search" class="size-5" />
          </div>
        </div>
      </div>
      <div class="inline-flex items-center gap-3 lg:gap-4">
        <button
          *ngIf="user"
          id="dropdownUserAvatarButton"
          data-dropdown-toggle="dropdownAvatar" class="flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600"
          type="button"
        >
          <span class="sr-only">Open user menu</span>
          <img *ngIf="user?.avatar" class="w-8 h-8 rounded-full" [height]="40" [width]="40" [ngSrc]="user.avatar || ''" alt="user photo">
          <span *ngIf="!user?.avatar" class="text-white w-8 h-8 rounded-full" style="align-content: center">
            {{initials}}
          </span>
        </button>

        <!-- Dropdown menu -->
        <div id="dropdownAvatar" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
          <div class="px-4 py-3 text-sm text-gray-900 dark:text-white">
            <div data-tooltip-target="full-name-tooltip" data-tooltip-placement="top">
              {{ user?.name }}
            </div>
            <div class="font-medium truncate" data-tooltip-target="email-tooltip" data-tooltip-placement="bottom">
              {{user?.email}}
            </div>
          </div>
          <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownUserAvatarButton">
            <li>
              <a class="disabled block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">
                Ajustes
              </a>
            </li>
          </ul>
          <div class="py-2">
            <a
              class="cursor-pointer block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"
              (click)="logout()"
            >
              Salir
            </a>
          </div>
        </div>

        <button
          *ngIf="!user"
          data-tooltip-target="login-tooltip"
          data-tooltip-placement="top"
          type="button"
          class="font-bold text-[13px] uppercase"
          (click)="login()"
        >
          <!--          routerLink="/login"-->
          <span class="hidden lg:block">Ingresar / Registro</span>
          <img
            src="/icons/login.svg"
            alt="login"
            class="size-5 lg:hidden"
          />
        </button>

        <!--        <a routerLink="/compare" class="relative hidden lg:block" data-tooltip-target="compare-tooltip"-->
        <!--           data-tooltip-placement="top">-->
        <!--          <span-->
        <!--            class="absolute -top-[3px] -right-[3px] flex items-center justify-center size-3 text-white bg-primary-900 rounded-full text-[9px]">-->
        <!--            0-->
        <!--          </span>-->
        <!--          <img-->
        <!--            src="/icons/compare.svg"-->
        <!--            alt="compare"-->
        <!--            class="size-5"-->
        <!--          />-->
        <!--        </a>-->
        <!--        <app-tooltip [tooltip-id]="'compare-tooltip'" [text]="'Comparar productos'" routerLink="/compare" />-->
        <button
          (click)="openCart($event)"
          data-tooltip-target="cart-tooltip" data-tooltip-placement="top"
          class="inline-flex gap-4">
          <div class="relative">
                  <span
                    class="absolute -top-[3px] -right-[3px] flex items-center justify-center size-3 text-white bg-primary-900 rounded-full text-[9px]">
                    {{ cartItemsLength }}
                  </span>
            <img src="/icons/cart.svg" alt="cart" class="size-5" />
          </div>
          <span class="text-[13px] font-bold hidden lg:block">
            {{ productSymbol(this.currency) }} {{ cartProductsTotal.toFixed(2) }}
          </span>
        </button>
      </div>
    </div>
  </div>
  <app-tooltip [tooltip-id]="'cart-tooltip'" [text]="'Carrito de compras'" />
  <app-tooltip [tooltip-id]="'login-tooltip'" [text]="'Iniciar sesión'" />
  <app-tooltip [tooltip-id]="'email-tooltip'" [text]="user?.email || ''" />
  <app-tooltip [tooltip-id]="'full-name-tooltip'" [text]="user?.fullName || ''" />
</header>

// app/components/shared/Header/Header.tsx
import { Link } from '@remix-run/react';
import { useEffect, useState } from 'react';

/* Extra */
import { useDispatch, useSelector } from 'react-redux';
import { Avatar, Dropdown, Tooltip } from 'flowbite-react';

/* Project */
import { AppDispatch, AppState } from '~/store/config';
import { HomeActions } from '~/store/home.store';
import { CartActions } from '~/store/cart.store';
import { LocalAuthService } from '~/services';
import './Header.css';

export const Header = () => {
  const [categories] = useState([]);
  const [initials] = useState(null);

  const { login, logout, checkSession } = LocalAuthService();

  useEffect(() => {
    checkSession();
  }, []);

  const user = useSelector((state: AppState) => state.home.user);
  const dispatch = useDispatch<AppDispatch>();

  const openSidebarMenu = () => {
    dispatch(HomeActions.showSidebar());
  };

  const toggleMenu = () => {
    console.log('toggleMenu');
  };

  const openCart = () => {
    dispatch(CartActions.showCartMenu());
  };

  return (
    <header className="pt-[5px] border-b">
      <div className="px-4 mx-auto max-w-df">
        <div className="h-16 lg:h-[105px] flex items-center gap-4 justify-between">
          <button
            id="menu-button"
            type="button"
            className="lg:hidden"
            onClick={openSidebarMenu}
          >
            <img src="/icons/menu.svg" alt="menu" className="size-5" />
          </button>

          <Link to="/">
            <img
              src="/images/logo.png"
              alt="logo"
              className="size-16 lg:size-[156px] object-contain"
            />
          </Link>

          <div className="relative flex-grow hidden lg:block">
            <input
              type="search"
              className="w-full border border-gray-200 rounded-full h-[46px] pl-[15px] pr-[230px]"
              placeholder="Buscar productos..."
            />
            <div>
              <button
                type="button"
                className="absolute inset-y-0 right-[45px] h-full px-4 bg-white border border-gray-200 text-[13px] text-[#777777] flex items-center w-44 justify-between"
                onClick={toggleMenu}
              >
                <span>CATEGORÍAS</span>
                <img src="/icons/rowd.svg" alt="rowd" className="size-3" />
              </button>

              <div
                className="absolute right-[45px] px-5 py-2 bg-white border
                            border-gray-200 shadow text-[#777777] text-sm
                            uppercase h-[320px] overflow-y-auto
                            scrollbar-thin scrollbar-thumb-gray-300
                            hover:scrollbar-thumb-gray-500
                            scrollbar-track-gray-100 z-10
                            navbar-categories {{ displayMenu  ? 'show' : 'hide' }}"
              >
                <ul className="space-y-2 [&>*>a:hover]:text-primary-600">
                  {categories.map((category) => (
                    <li key={category}>
                      <Link to="/public">{category}</Link>
                    </li>
                  ))}
                </ul>
              </div>

              <div className="absolute inset-y-0 right-0 w-[50px] flex items-center justify-center">
                <img src="/icons/search.svg" alt="search" className="size-5" />
              </div>
            </div>
          </div>

          <div className="inline-flex items-center gap-3 lg:gap-4">
            {user && (
              <div>
                <Dropdown
                  label={
                    user.avatar ? (
                      <Avatar alt="User settings" img={user.avatar} rounded />
                    ) : (
                      <span
                        className="text-white w-8 h-8 rounded-full"
                        style={{ alignContent: 'center' }}
                      >
                        {initials}
                      </span>
                    )
                  }
                  arrowIcon={false}
                  inline
                >
                  <Dropdown.Header>
                    <span className="block text-sm">{user.name}</span>
                    <span className="block truncate text-sm font-medium">
                      {user.email}
                    </span>
                  </Dropdown.Header>
                  <Dropdown.Item>Settings</Dropdown.Item>
                  <Dropdown.Divider />
                  <Dropdown.Item onClick={logout}>Sign out</Dropdown.Item>
                </Dropdown>
              </div>
            )}

            <div
              id="dropdownAvatar"
              className="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600"
            >
              <div className="px-4 py-3 text-sm text-gray-900 dark:text-white">
                <div
                  data-tooltip-target="full-name-tooltip"
                  data-tooltip-placement="top"
                >
                  {user?.name}
                </div>
                <div
                  className="font-medium truncate"
                  data-tooltip-target="email-tooltip"
                  data-tooltip-placement="bottom"
                >
                  {user?.email}
                </div>
              </div>
              <ul
                className="py-2 text-sm text-gray-700 dark:text-gray-200"
                aria-labelledby="dropdownUserAvatarButton"
              >
                <li>
                  <Link
                    to="/public"
                    className="disabled block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                  >
                    Ajustes
                  </Link>
                </li>
              </ul>
              <div className="py-2">
                <button
                  className="cursor-pointer block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"
                  onClick={logout}
                >
                  Salir
                </button>
              </div>
            </div>

            {!user && (
              <button
                data-tooltip-target="login-tooltip"
                data-tooltip-placement="top"
                type="button"
                className="font-bold text-[13px] uppercase"
                onClick={login}
              >
                <span className="hidden lg:block">Ingresar / Registro</span>
                <img
                  src="/icons/login.svg"
                  alt="login"
                  className="size-5 lg:hidden"
                />
              </button>
            )}

            <button onClick={openCart} className="inline-flex gap-4">
              <div className="relative">
                <span className="absolute -top-[3px] -right-[3px] flex items-center justify-center size-3 text-white bg-primary-900 rounded-full text-[9px]">
                  {0}
                </span>
                <Tooltip content="Carrito" className="text-xs">
                  <img src="/icons/cart.svg" alt="cart" className="size-5" />
                </Tooltip>
              </div>
              <span className="text-[13px] font-bold hidden lg:block">
                S/. 0
              </span>
            </button>
          </div>
        </div>
      </div>
    </header>
  );
};
