// src/app/shared/modal-overlay/modal-overlay.component.ts
import { Component } from '@angular/core';

/* Project */
import { HomeStateProvider } from '@app/providers/home-state.provider';

@Component({
  selector: 'modal-overlay',
  standalone: true,
  imports: [],
  templateUrl: './modal-overlay.component.html',
  styleUrl: './modal-overlay.component.scss',
})
export class ModalOverlayComponent {
  display = false;

  constructor(private readonly homeStateProvider: HomeStateProvider) {
    this.homeStateProvider.modalActive$.subscribe((value) => {
      this.display = value;
    });
  }
}

<div
  class="fixed inset-0 z-50 flex items-end bg-black/50 sm:items-center sm:justify-center modal-overlay {{display ? 'show' : 'hide' }}"
  aria-hidden="true"
>
<!--  x-transition:enter="transition ease-in-out duration-150"-->
<!--  x-transition:enter-start="opacity-0"-->
<!--  x-transition:enter-end="opacity-100"-->
<!--  x-transition:leave="transition ease-in-out duration-150"-->
<!--  x-transition:leave-start="opacity-100"-->
<!--  x-transition:leave-end="opacity-0"-->
</div>

// app/components/shared/ModalOverlay/ModalOverlay.tsx
/* Project */
import { useSelector } from 'react-redux';

/* Project */
import { AppState } from '~/store/config';
import './ModalOverlay.css';

export const ModalOverlay = () => {
  const display = useSelector((state: AppState) => state.home.modalOverlay);
  console.log({ display });

  return (
    <div
      style={{ display: 'none' }}
      className={`fixed inset-0 z-50 flex items-end bg-black/50 sm:items-center sm:justify-center modal-overlay ${display && 'show'}`}
      aria-hidden="true"
    ></div>
  );
};
