// src/app/components/home/main-slider/main-slider.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, OnInit } from '@angular/core';

/* Extra */
import Swiper from 'swiper';
import { Autoplay, Navigation, Pagination } from 'swiper/modules';

@Component({
  selector: 'app-main-slider',
  standalone: true,
  imports: [],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './main-slider.component.html',
  styleUrls: ['./main-slider.component.css'],
})
export class MainSliderComponent implements OnInit {
  constructor() {}

  ngOnInit() {
    // setTimeout(() => {
    new Swiper('.main-slider', {
      modules: [Autoplay, Pagination, Navigation],
      slidesPerView: 1,
      spaceBetween: 30,
      loop: true,
      grabCursor: true,
      autoplay: {
        delay: 2500,
        disableOnInteraction: false,
      },
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
    });
    // });
  }
}

<div class="flex gap-4 mb-[50px] lg:justify-end">
  <div class="w-full lg:w-4/5" id="banners">
    <!-- Slider main container -->
    <div class="swiper h-[380px] lg:h-[491px] lg:ml-4 main-slider">
      <!-- Additional required wrapper -->
      <div class="swiper-wrapper">
        <!-- Slides -->
        <div class="swiper-slide">
          <img
            src="https://gamerbit.pe/wp-content/uploads/2022/09/AMD-RYZEN-SERIE-7000-ZEN-4.jpg"
            alt=""
            class="object-fill size-full"
          />
        </div>
        <div class="swiper-slide">
          <img
            src="https://gamerbit.pe/wp-content/uploads/2023/10/GAMERBIT-BANER.png"
            alt=""
            class="object-fill size-full"
          />
        </div>
        <div class="swiper-slide">
          <img
            src="https://gamerbit.pe/wp-content/uploads/revslider/electronics-1/BANER-01.jpg"
            alt=""
            class="object-fill size-full"
          />
        </div>
        <div class="swiper-slide">
          <img
            src="https://gamerbit.pe/wp-content/uploads/2022/06/gamerbit-banner.jpg"
            alt=""
            class="object-fill size-full"
          />
        </div>
      </div>
      <div class="swiper-button-next"></div>
      <div class="swiper-button-prev"></div>
      <div class="swiper-pagination"></div>

    </div>

  </div>
</div>

// app/components/Home/MainSlider/MainSlider.tsx
/* Project */
import { Swiper, SwiperSlide } from 'swiper/react';
import { Autoplay, Navigation, Pagination } from 'swiper/modules';
import 'swiper/css';

export const MainSlider = () => {
  return (
    <div className="flex gap-4 mb-[50px] lg:justify-end">
      <div className="w-full lg:w-4/5" id="banners">
        <Swiper
          loop
          modules={[Autoplay, Pagination, Navigation]}
          spaceBetween={30}
          slidesPerView={1}
          // onSlideChange={() => console.log('slide change')}
          autoplay={{
            delay: 2500,
            disableOnInteraction: false,
          }}
          pagination={{
            type: 'bullets',
          }}
          navigation={{
            enabled: true,
          }}
        >
          <SwiperSlide>
            <img
              src="https://gamerbit.pe/wp-content/uploads/2022/09/AMD-RYZEN-SERIE-7000-ZEN-4.jpg"
              alt=""
              className="object-fill size-full"
            />
          </SwiperSlide>
          <SwiperSlide>
            <img
              src="https://gamerbit.pe/wp-content/uploads/2023/10/GAMERBIT-BANER.png"
              alt=""
              className="object-fill size-full"
            />
          </SwiperSlide>
          <SwiperSlide>
            <img
              src="https://gamerbit.pe/wp-content/uploads/revslider/electronics-1/BANER-01.jpg"
              alt=""
              className="object-fill size-full"
            />
          </SwiperSlide>
          <SwiperSlide>
            <img
              src="https://gamerbit.pe/wp-content/uploads/2022/06/gamerbit-banner.jpg"
              alt=""
              className="object-fill size-full"
            />
          </SwiperSlide>
        </Swiper>
      </div>
    </div>
  );
};
