// app/components/shared/ProductItemCarrousel/ProductItemCarrousel.tsx
import { MouseEvent, useMemo, useState } from 'react';
import { useNavigate } from '@remix-run/react';

/* Extra */
import { useDispatch } from 'react-redux';
import { Tooltip } from 'flowbite-react';

/* Project */
import { TProduct } from '~/types';
import './ProductItemCarrousel.css';
import { HomeActions } from '~/store/home.store';
import { CartActions } from '~/store/cart.store';

type ProductItemCarrouselProps = {
  product: TProduct;
};

export const ProductItemCarrousel = (props: ProductItemCarrouselProps) => {
  const { product } = props;

  const navigate = useNavigate();
  const [selectedWarehouse, setSelectedWarehouse] = useState(0);
  const [displayMenu, setDisplayMenu] = useState(false);
  const dispatch = useDispatch();

  const trimmedName = useMemo(() => {
    const currentLength = product.name.length;

    if (currentLength <= 50) return product.name;

    return product.name.trim().substring(0, 50) + '...';
  }, [product]);
  const priceText = `S./ ${product.pricePEN}`;

  const redirectToDetail = () => {
    navigate(`/products/${product.id}`);
  };

  const setProductModal = (event: MouseEvent) => {
    event.stopPropagation();
    dispatch(HomeActions.setProductModal({ productModal: product }));
  };

  const stopPropagationOnEvent = () => {
    console.log('stopPropationOnEvent');
  };

  const hideMenu = (event: MouseEvent) => {
    event.stopPropagation();
    setDisplayMenu(false);
  };

  const setWarehouse = (event: MouseEvent, warehouseId: number) => {
    event.stopPropagation();
    setSelectedWarehouse(warehouseId);
  };

  const filterTags = (event: MouseEvent, id: number) => {
    event.stopPropagation();

    console.log('filterTags', id);
  };

  const toggleMenu = (event: MouseEvent) => {
    event.stopPropagation();
    setDisplayMenu((prev) => !prev);
  };

  const addToCart = (event: MouseEvent) => {
    event.stopPropagation();
    dispatch(
      CartActions.addProductToCart({
        cartProduct: {
          ...product,
          quantity: 1,
          warehouse: selectedWarehouse,
        },
        openCartMenu: true,
      }),
    );
  };

  return (
    <div className="group cursor-pointer" onClick={redirectToDetail}>
      <div className="relative overflow-hidden">
        <div className="absolute right-0 hidden transition-all duration-200 translate-x-12 opacity-0 lg:block group-hover:opacity-100 group-hover:translate-x-0">
          <div className="flex flex-col">
            <Tooltip content="Vista previa" placement="left">
              <a
                onClick={setProductModal}
                className="cursor-pointer size-[50px] bg-white flex justify-center items-center shadow-sm border-r"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth="1.5"
                  stroke="currentColor"
                  className="size-6"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z"
                  />
                </svg>
              </a>
            </Tooltip>
          </div>
        </div>
        <div
          onClick={stopPropagationOnEvent}
          className={`prd-item-menu absolute inset-0 flex flex-col items-center justify-end gap-4 origin-bottom bg-white/90 ${displayMenu ? 'show' : 'hide'}`}
        >
          <button
            type="button"
            className="absolute top-0 right-0 flex items-center gap-1 text-xs font-semibold uppercase"
            onClick={hideMenu}
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth="2"
              stroke="currentColor"
              className="w-3 h-3"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M6 18 18 6M6 6l12 12"
              />
            </svg>
            Cerrar
          </button>
          <div className="text-center">
            <span className="block mb-2.5 text-sm font-semibold">Almacén:</span>
            <div>
              <ul className="flex items-center gap-2 [&>*>span]:border [&>*>span]:border-gray-300 [&>*>span]:bg-white [&>*>span]:px-3 [&>*>span]:py-1 [&>*>span]:rounded-md mb-5 [&>*>span]:cursor-pointer [&>*>span:hover]:border-gray-300 [&>*>span:hover]:border-2 transition-all">
                {product?.warehouses.map((warehouse) => (
                  <li
                    key={warehouse.id}
                    onClick={(evt) => setWarehouse(evt, warehouse.id)}
                  >
                    <span
                      className={`${selectedWarehouse === warehouse.id ? '!border-2 !border-black' : ''}`}
                    >
                      {warehouse.name}
                    </span>
                  </li>
                ))}
              </ul>
              {selectedWarehouse === 0 && (
                <span className="block mb-2.5 text-sm font-semibold text-black">
                  Seleccione un almacén
                </span>
              )}
              <div className="flex flex-col items-center gap-5">
                <div className="inline-flex items-center">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth="2"
                    stroke="currentColor"
                    className="w-5 h-5 text-green-500"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="m4.5 12.75 6 6 9-13.5"
                    />
                  </svg>
                  <p className="text-sm font-semibold">
                    <span>{product.stock}</span> Disponibles
                  </p>
                </div>
              </div>
            </div>
          </div>
          <button
            onClick={addToCart}
            disabled={selectedWarehouse === 0}
            type="button"
            className={`w-full py-2.5 text-white uppercase ${selectedWarehouse === 0 ? 'bg-gray-400' : 'bg-primary-900 text-[13px] hover:bg-primary-950 transition'}`}
          >
            Añadir al carrito
          </button>
        </div>
        <img src={product.image} alt="" />
      </div>
      <div className="flex flex-col items-center px-3 pt-4 pb-5 text-center transition-all duration-200 rounded h-[230px] justify-between">
        <div>
          <h3 className="mb-3 text-sm font-medium text-black font-poppins">
            {trimmedName}
          </h3>
          <ul className="flex flex-wrap gap-1 text-xs text-gray-400 uppercase mb-2 [&>*>a:hover]:text-primary-900 justify-center">
            {product?.tags.map((tag) => (
              <li key={tag.id} onClick={(evt) => filterTags(evt, tag.id)}>
                <a className="cursor-pointer">{tag.name}</a>
              </li>
            ))}
          </ul>
        </div>
        <div className="flex flex-col items-center">
          <span className="block mb-6 text-lg font-semibold text-primary-900">
            {priceText}
          </span>
          <a
            onClick={(evt) => toggleMenu(evt)}
            className="cursor-pointer relative flex items-center justify-center gap-2 overflow-hidden text-[13px] font-semibold text-white uppercase transition rounded-full max-w-fit hover:bg-primary-950 bg-primary-900 group/cart before:content-cart before:absolute before:size-5 before:translate-y-full before:opacity-0 hover:before:translate-y-0 hover:before:opacity-100 before:transition-all before:duration-200 before:ease-in-out before:flex before:items-center before:justify-center flex-shrink-0"
          >
            <span className="block px-4 py-3 leading-4 transition-transform group-hover/cart:-translate-y-full">
              Comprar
            </span>
          </a>
        </div>
      </div>
    </div>
  );
};

// src/app/shared/product-item-carrousel/product-item-carrousel.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { NgForOf, NgIf } from '@angular/common';
import { Router } from '@angular/router';

/* Project */
import { TProduct } from '@app/types';
import { TooltipComponent } from '@app/shared/tooltip/tooltip.component';
import { HomeStateProvider } from '@app/providers/home-state.provider';
import { productPrice, productSymbol } from '@app/helpers';

@Component({
  selector: 'app-product-item-carrousel',
  standalone: true,
  imports: [TooltipComponent, NgForOf, NgIf],
  templateUrl: './product-item-carrousel.component.html',
  styleUrl: './product-item-carrousel.component.scss',
})
export class ProductItemCarrouselComponent implements OnInit {
  @Input({
    alias: 'product',
    required: true,
  })
  product!: TProduct;

  @Input({
    alias: 'key',
    required: true,
  })
  key!: string;

  currency!: string;
  displayMenu: boolean = false;
  selectedWarehouse: number = 0;
  baseIdentifier: string = '';
  priceText!: string;

  constructor(
    private readonly router: Router,
    private readonly homeStateProvider: HomeStateProvider,
  ) {}

  get trimmedName() {
    const currentLength = this.product.name.length;

    if (currentLength <= 50) {
      return this.product.name;
    }

    return this.product.name.trim().substring(0, 50) + '...';
  }

  ngOnInit() {
    this.baseIdentifier = `${this.key}-product-${this.product.id}`;

    this.homeStateProvider.selectedCurrency$.subscribe((currency) => {
      this.currency = currency;
      this.priceText =
        productSymbol(currency) + productPrice(currency, this.product);
    });
  }

  toggleMenu(event: Event) {
    event.stopPropagation();
    this.displayMenu = !this.displayMenu;
  }

  hideMenu() {
    this.displayMenu = false;
  }

  addToCart(event: Event) {
    event.stopPropagation();
    console.log({
      id: this.product.id,
      quantity: 1,
      warehouse: this.selectedWarehouse,
    });

    this.homeStateProvider.addProductToCart(
      {
        id: this.product.id,
        quantity: 1,
        warehouse: this.selectedWarehouse,
        name: this.product.name,
        pricePEN: this.product.pricePEN,
        priceUSD: this.product.priceUSD,
        priceEUR: this.product.priceEUR,
        image: this.product.image,
      },
      true,
    );

    this.displayMenu = false;
    this.selectedWarehouse = 0;
  }

  setWarehouse(event: Event, id: number) {
    event.stopPropagation();
    this.selectedWarehouse = id;
  }

  setProductModal(event: Event) {
    event.stopPropagation();
    this.homeStateProvider.setProductModal(this.product);
  }

  stopButton(event: Event) {
    event.preventDefault();
    event.stopPropagation();
  }

  filterTags(event: Event, tag: number) {
    event.preventDefault();
    event.stopPropagation();
    console.log({ tag });
  }

  async redirectToDetail() {
    await this.router.navigate([`/products/${this.product.id}`]);
  }

  protected readonly Number = Number;
}

<div class="group" (click)="redirectToDetail()">
  <div class="relative overflow-hidden">
    <div
      class="absolute right-0 hidden transition-all duration-200 translate-x-12 opacity-0 lg:block group-hover:opacity-100 group-hover:translate-x-0"
    >
      <div class="flex flex-col">
        <!--        <app-tooltip [tooltip-id]="baseIdentifier+'-compare'" [text]="'Comparar productos'" />-->
        <!--        <a-->
        <!--          routerLink="/"-->
        <!--          class="size-[50px] bg-white flex justify-center items-center shadow-sm border-r"-->
        <!--          [attr.data-tooltip-target]="baseIdentifier+'-compare'"-->
        <!--          data-tooltip-placement="left"-->
        <!--        >-->
        <!--          <svg-->
        <!--            xmlns="http://www.w3.org/2000/svg"-->
        <!--            fill="none"-->
        <!--            viewBox="0 0 24 24"-->
        <!--            stroke-width="1.5"-->
        <!--            stroke="currentColor"-->
        <!--            class="size-6"-->
        <!--          >-->
        <!--            <path-->
        <!--              stroke-linecap="round"-->
        <!--              stroke-linejoin="round"-->
        <!--              d="M19.5 12c0-1.232-.046-2.453-.138-3.662a4.006 4.006 0 0 0-3.7-3.7 48.678 48.678 0 0 0-7.324 0 4.006 4.006 0 0 0-3.7 3.7c-.017.22-.032.441-.046.662M19.5 12l3-3m-3 3-3-3m-12 3c0 1.232.046 2.453.138 3.662a4.006 4.006 0 0 0 3.7 3.7 48.656 48.656 0 0 0 7.324 0 4.006 4.006 0 0 0 3.7-3.7c.017-.22.032-.441.046-.662M4.5 12l3 3m-3-3-3 3"-->
        <!--            />-->
        <!--          </svg>-->
        <!--        </a>-->
        <app-tooltip [tooltip-id]="baseIdentifier+'-preview'" [text]="'Vista previa'" />
        <a
          (click)="setProductModal($event)"
          class="cursor-pointer size-[50px] bg-white flex justify-center items-center shadow-sm border-r"
          [attr.data-tooltip-target]="baseIdentifier+'-preview'"
          data-tooltip-placement="left"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="size-6"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z"
            />
          </svg>
        </a>
      </div>
    </div>
    <div
      (click)="stopButton($event)"
      class="prd-item-menu absolute inset-0 flex flex-col items-center justify-end gap-4 origin-bottom bg-white/90 {{displayMenu ? 'show' : 'hide'}}"
    >
      <button
        type="button"
        class="absolute top-0 right-0 flex items-center gap-1 text-xs font-semibold uppercase"
        (click)="hideMenu()"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke-width="2"
          stroke="currentColor"
          class="w-3 h-3"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M6 18 18 6M6 6l12 12"
          />
        </svg>
        Cerrar
      </button>
      <div class="text-center">
        <span class="block mb-2.5 text-sm font-semibold">
          Almacén:
        </span>
        <div>
          <ul
            class="flex items-center gap-2 [&>*>span]:border [&>*>span]:border-gray-300 [&>*>span]:bg-white [&>*>span]:px-3 [&>*>span]:py-1 [&>*>span]:rounded-md mb-5 [&>*>span]:cursor-pointer [&>*>span:hover]:border-gray-300 [&>*>span:hover]:border-2 transition-all"
          >
            <!-- DISABLE WITH class="!opacity-60" -->
            <li *ngFor="let warehouse of product.warehouses" (click)="setWarehouse($event, warehouse.id)">
              <span class="{{selectedWarehouse === warehouse.id ? '!border-2 !border-black' : ''}}">
                {{ warehouse.name }}
              </span>
            </li>
          </ul>
          <span class="block mb-2.5 text-sm font-semibold text-black"
                *ngIf="selectedWarehouse === 0">
                Seleccione un almacén
              </span>
          <div class="flex flex-col items-center gap-5">
            <!--            <button-->
            <!--              *ngIf="selectedWarehouse !== 0"-->
            <!--              (click)="setWarehouse(0)"-->
            <!--              type="button"-->
            <!--              class="inline-flex items-center gap-1 text-xs"-->
            <!--            >-->
            <!--              <svg-->
            <!--                xmlns="http://www.w3.org/2000/svg"-->
            <!--                fill="none"-->
            <!--                viewBox="0 0 24 24"-->
            <!--                stroke-width="1.5"-->
            <!--                stroke="currentColor"-->
            <!--                class="w-4 h-4"-->
            <!--              >-->
            <!--                <path-->
            <!--                  stroke-linecap="round"-->
            <!--                  stroke-linejoin="round"-->
            <!--                  d="M6 18 18 6M6 6l12 12"-->
            <!--                />-->
            <!--              </svg>-->
            <!--              Limpiar-->
            <!--            </button>-->
            <div class="inline-flex items-center">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                stroke-width="2"
                stroke="currentColor"
                class="w-5 h-5 text-green-500"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  d="m4.5 12.75 6 6 9-13.5"
                />
              </svg>
              <p class="text-sm font-semibold">
                <span>{{ product.stock }}</span> Disponibles
              </p>
            </div>
          </div>
        </div>
      </div>
      <button
        (click)="addToCart($event)"
        [disabled]="selectedWarehouse === 0"
        type="button"
        class="w-full py-2.5 text-white uppercase {{selectedWarehouse === 0 ? 'bg-gray-400' : 'bg-primary-900 text-[13px] hover:bg-primary-950 transition'}}"
      >
        Añadir al carrito
      </button>
    </div>
    <img
      src="{{product.image}}"
      alt=""
    />
  </div>
  <div
    class="flex flex-col items-center px-3 pt-4 pb-5 text-center transition-all duration-200 rounded h-[230px] justify-between"
  >
    <div>
      <h3
        class="mb-3 text-sm font-medium text-black font-poppins"
      >
        {{ trimmedName }}
      </h3>
      <ul
        class="flex flex-wrap gap-1 text-xs text-gray-400 uppercase mb-2 [&>*>a:hover]:text-primary-900 justify-center"
      >
        <li (click)="filterTags($event, tag.id)" *ngFor="let tag of product.tags"><a class="cursor-pointer">{{ tag.name }}</a></li>
      </ul>
    </div>
    <div class="flex flex-col items-center">
      <span class="block mb-6 text-lg font-semibold text-primary-900">
       {{ priceText }}
      </span>
      <a
        (click)="toggleMenu($event)"
        class="cursor-pointer relative flex items-center justify-center gap-2 overflow-hidden text-[13px] font-semibold text-white uppercase transition rounded-full max-w-fit hover:bg-primary-950 bg-primary-900 group/cart before:content-cart before:absolute before:size-5 before:translate-y-full before:opacity-0 hover:before:translate-y-0 hover:before:opacity-100 before:transition-all before:duration-200 before:ease-in-out before:flex before:items-center before:justify-center flex-shrink-0"
      >
        <span
          class="block px-4 py-3 leading-4 transition-transform group-hover/cart:-translate-y-full"
        >
          Comprar
        </span>
      </a>
    </div>
  </div>
</div>
