// app/components/shared/WhatsappPopUp/WhatsappPopUp.tsx
import { useCallback, useRef } from 'react';

/* Extra */
import { useDispatch, useSelector } from 'react-redux';

/* Project */
import { AppDispatch, AppState } from '~/store/config';
import { HomeActions } from '~/store/home.store';
import { useOutside } from '~/hooks';
import './WhatsappPopUp.css';

export const WhatsappPopUp = () => {
  const display = useSelector((state: AppState) => state.home.whatsappPopUp);
  const dispatch = useDispatch<AppDispatch>();

  const ref = useRef<any>(null);

  const togglePopUp = () => {
    dispatch(
      display
        ? HomeActions.hideWhatsappPopUp()
        : HomeActions.showWhatsappPopUp(),
    );
  };

  const closePopUp = useCallback(() => {
    dispatch(HomeActions.hideWhatsappPopUp());
  }, [dispatch]);

  useOutside(ref, closePopUp, display);

  return (
    <div ref={ref}>
      <div className="!font-poppins group">
        <div
          className={`absolute inset-0 overflow-hidden bg-white rounded-lg shadow-lg md:left-auto md:top-auto md:right-6 md:bottom-[95px] wsp-popup ${
            display && 'show'
          }`}
          style={{ position: 'fixed', zIndex: 1000, display: 'none' }}
        >
          <div className="bg-[#20C380] text-white relative text-center px-7 py-6">
            <p className="mb-2 text-lg font-bold">¿Necesitas ayuda?</p>
            <span className="text-sm">
              Haga clic en uno de nuestros representantes
            </span>
            <button
              onClick={closePopUp}
              className="absolute left-auto right-[8px] text-white outline-none top-2"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="w-6 h-6 stroke-current"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M6 18L18 6M6 6l12 12"
                ></path>
              </svg>
            </button>
          </div>
          <div className="px-5 py-4 space-y-5 bg-white">
            <a
              onClick={closePopUp}
              className="block"
              href="https://web.whatsapp.com/send?phone=+51998800769&amp;text=Hola%20MG%20Solutiones%20Quiero%20Información,%20vengo%20desde%20su%20página%20web"
              target="_blank"
              rel="noreferrer"
            >
              <div className="bg-[#F6F7F9] py-2.5 px-3 rounded-lg hover:border-[#20C380] hover:bg-transparent border-2 border-transparent transition-all ease-linear duration-200">
                <div className="relative flex space-x-4">
                  <div className="rounded-full">
                    <img
                      src="/images/logo.png"
                      alt="MGSoluciones"
                      className="rounded-full h-16 w-16 !border-[3px] object-contain p-1"
                      style={{ border: '3px solid #20c380' }}
                    />
                  </div>
                  <div className="space-y-[2px]" style={{ textAlign: 'left' }}>
                    <h3 className="text-[#343537] font-bold !font-poppins !text-lg !leading-none">
                      MG Solutions
                    </h3>
                    <p className="text-[#B5B6B8] !text-xs">Asesor Web</p>
                    <span className="select-none bg-[#20C380] py-1 px-3 rounded-md inline-block text-white text-xs !mt-2">
                      Conectado
                    </span>
                  </div>
                </div>
              </div>
            </a>
          </div>
        </div>
        <div
          onClick={togglePopUp}
          className="cursor-pointer bg-[#20C380] right-5 left-auto bottom-5 h-16 w-16 rounded-full flex justify-center items-center shadow-lg group-hover:shadow-[#20C380] transition-shadow duration-500 ease-in-out animate-jump animate-delay-1000 fixed z-10"
        >
          <svg
            viewBox="0 0 32 32"
            className="text-white fill-current w-14 h-14"
          >
            <path
              d=" M19.11 17.205c-.372 0-1.088 1.39-1.518 1.39a.63.63 0 0 1-.315-.1c-.802-.402-1.504-.817-2.163-1.447-.545-.516-1.146-1.29-1.46-1.963a.426.426 0 0 1-.073-.215c0-.33.99-.945.99-1.49 0-.143-.73-2.09-.832-2.335-.143-.372-.214-.487-.6-.487-.187 0-.36-.043-.53-.043-.302 0-.53.115-.746.315-.688.645-1.032 1.318-1.06 2.264v.114c-.015.99.472 1.977 1.017 2.78 1.23 1.82 2.506 3.41 4.554 4.34.616.287 2.035.888 2.722.888.817 0 2.15-.515 2.478-1.318.13-.33.244-.73.244-1.088 0-.058 0-.144-.03-.215-.1-.172-2.434-1.39-2.678-1.39zm-2.908 7.593c-1.747 0-3.48-.53-4.942-1.49L7.793 24.41l1.132-3.337a8.955 8.955 0 0 1-1.72-5.272c0-4.955 4.04-8.995 8.997-8.995S25.2 10.845 25.2 15.8c0 4.958-4.04 8.998-8.998 8.998zm0-19.798c-5.96 0-10.8 4.842-10.8 10.8 0 1.964.53 3.898 1.546 5.574L5 27.176l5.974-1.92a10.807 10.807 0 0 0 16.03-9.455c0-5.958-4.842-10.8-10.802-10.8z"
              fillRule="evenodd"
            ></path>
          </svg>
        </div>
      </div>
    </div>
  );
};

// src/app/shared/whatsapp-popup/whatsapp-popup.component.ts
import {
  Component,
  ElementRef,
  OnDestroy,
  Renderer2,
  ViewChild,
} from '@angular/core';

@Component({
  selector: 'whatsapp-popup',
  standalone: true,
  imports: [],
  templateUrl: './whatsapp-popup.component.html',
  styleUrl: './whatsapp-popup.component.css',
})
export class WhatsappPopupComponent implements OnDestroy {
  @ViewChild('wspPopUpDiv', { static: true }) elementRef!: ElementRef;
  private readonly outsideListener: () => void;
  display: boolean = false;

  constructor(private renderer: Renderer2) {
    this.outsideListener = this.renderer.listen(
      'window',
      'click',
      this.outsideCallback.bind(this),
    );
  }

  togglePopUp() {
    this.display = !this.display;
  }

  closePopUp() {
    this.display = false;
  }

  outsideCallback(event: Event) {
    const outside = !this.elementRef.nativeElement.contains(event.target);

    if (outside) this.display = false;
  }

  ngOnDestroy() {
    if (this.outsideListener) this.outsideListener();
  }
}

<div class="!font-poppins group" #wspPopUpDiv>
  <div
    class="absolute inset-0 overflow-hidden bg-white rounded-lg shadow-lg md:left-auto md:top-auto md:right-6 md:bottom-[95px] wsp-popup {{
    display ? 'show' : 'hide'
    }}"
    style="position: fixed; z-index: 1000"
  >
    <div class="bg-[#20C380] text-white relative text-center px-7 py-6">
      <p class="mb-2 text-lg font-bold">¿Necesitas ayuda?</p>
      <span class="text-sm"
      >Haga clic en uno de nuestros representantes</span
      >
      <button
        (click)="closePopUp()"
        class="absolute left-auto right-[8px] text-white outline-none top-2"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="w-6 h-6 stroke-current"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M6 18L18 6M6 6l12 12"
          ></path>
        </svg>
      </button>
    </div>
    <div class="px-5 py-4 space-y-5 bg-white">
      <a
        (click)="closePopUp()"
        class="block"
        href="https://web.whatsapp.com/send?phone=+51998800769&amp;text=Hola%20MG%20Solutiones%20Quiero%20Información,%20vengo%20desde%20su%20página%20web"
        target="_blank"
      >
        <div
          class="bg-[#F6F7F9] py-2.5 px-3 rounded-lg hover:border-[#20C380] hover:bg-transparent border-2 border-transparent transition-all ease-linear duration-200"
        >
          <div class="relative flex space-x-4">
            <div class="rounded-full">
              <img
                src="/images/logo.png"
                alt="MGSoluciones"
                class="rounded-full h-16 w-16 !border-[3px] object-contain p-1"
                style="border: 3px solid #20c380"
              />
            </div>
            <div class="space-y-[2px]" style="text-align: left">
              <h3
                class="text-[#343537] font-bold !font-poppins !text-lg !leading-none"
              >
                MG Solutions
              </h3>
              <p class="text-[#B5B6B8] !text-xs">Asesor Web</p>
              <span
                class="select-none bg-[#20C380] py-1 px-3 rounded-md inline-block text-white text-xs !mt-2"
              >Conectado</span
              >
            </div>
          </div>
        </div>
      </a>
    </div>
  </div>
  <div
    (click)="togglePopUp()"
    class="cursor-pointer bg-[#20C380] right-5 left-auto bottom-5 h-16 w-16 rounded-full flex justify-center items-center shadow-lg group-hover:shadow-[#20C380] transition-shadow duration-500 ease-in-out animate-jump animate-delay-1000 fixed z-10"
  >
    <svg viewBox="0 0 32 32" class="text-white fill-current w-14 h-14">
      <path
        d=" M19.11 17.205c-.372 0-1.088 1.39-1.518 1.39a.63.63 0 0 1-.315-.1c-.802-.402-1.504-.817-2.163-1.447-.545-.516-1.146-1.29-1.46-1.963a.426.426 0 0 1-.073-.215c0-.33.99-.945.99-1.49 0-.143-.73-2.09-.832-2.335-.143-.372-.214-.487-.6-.487-.187 0-.36-.043-.53-.043-.302 0-.53.115-.746.315-.688.645-1.032 1.318-1.06 2.264v.114c-.015.99.472 1.977 1.017 2.78 1.23 1.82 2.506 3.41 4.554 4.34.616.287 2.035.888 2.722.888.817 0 2.15-.515 2.478-1.318.13-.33.244-.73.244-1.088 0-.058 0-.144-.03-.215-.1-.172-2.434-1.39-2.678-1.39zm-2.908 7.593c-1.747 0-3.48-.53-4.942-1.49L7.793 24.41l1.132-3.337a8.955 8.955 0 0 1-1.72-5.272c0-4.955 4.04-8.995 8.997-8.995S25.2 10.845 25.2 15.8c0 4.958-4.04 8.998-8.998 8.998zm0-19.798c-5.96 0-10.8 4.842-10.8 10.8 0 1.964.53 3.898 1.546 5.574L5 27.176l5.974-1.92a10.807 10.807 0 0 0 16.03-9.455c0-5.958-4.842-10.8-10.802-10.8z"
        fill-rule="evenodd"
      ></path>
    </svg>
  </div>
</div>
