// src/app/components/home/featured-products/featured-products.component.ts
import { Component, Input } from '@angular/core';
import { ProductCarrouselComponent } from '@app/shared/product-carrousel/product-carrousel.component';

@Component({
  selector: 'app-featured-products',
  standalone: true,
  imports: [ProductCarrouselComponent],
  templateUrl: './featured-products.component.html',
  styleUrl: './featured-products.component.scss',
})
export class FeaturedProductsComponent {
  @Input({ required: true }) key!: string;
  @Input({ required: true }) title!: string;
}

<div class="py-14 {{key}} navSwiper">
  <h4 class="text-[22px] font-semibold font-poppins mb-5">
    {{title.toUpperCase()}}
  </h4>

  <app-product-carrousel [key]="key" />
</div>

// app/components/Home/FeaturedProducts/FeaturedProducts.tsx
type FeaturedProductsProps = {
  title: string;
};

export const FeaturedProducts = (props: FeaturedProductsProps) => {
  const { title } = props;

  return (
    <div className="py-14 {{key}} navSwiper">
      <h4 className="text-[22px] font-semibold font-poppins mb-5">
        {title.toUpperCase()}
      </h4>

      {/*<app-product-carrousel />*/}
    </div>
  );
};
