// src/app/shared/navbar-item/navbar-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { NgForOf, NgIf } from '@angular/common';

/* Project */
import { TCategory } from '@app/types';
import { HomeStateProvider } from '@app/providers/home-state.provider';
import { NavbarSubItemComponent } from '@app/shared/navbar-sub-item/navbar-sub-item.component';

@Component({
  selector: 'app-navbar-item',
  standalone: true,
  imports: [NgForOf, NgIf, NavbarSubItemComponent],
  templateUrl: './navbar-item.component.html',
  styleUrl: './navbar-item.component.scss',
})
export class NavbarItemComponent implements OnInit {
  @Input({
    alias: 'category',
    required: true,
  })
  category!: TCategory;
  isSelected!: boolean;
  protected readonly Array = Array;

  constructor(private homeStateProvider: HomeStateProvider) {}

  ngOnInit() {
    setTimeout(() => {
      this.homeStateProvider.selectedCategory$.subscribe(
        (selectedCategoryId) => {
          this.isSelected = selectedCategoryId === this.category.id;
        },
      );
    });
  }

  setSelectedCategoryId() {
    this.homeStateProvider.setSelectedCategoryId(this.category.id);
  }

  removeSelectedCategoryId() {
    this.homeStateProvider.setSelectedCategoryId(0);
  }
}

<li
  class="{{isSelected ? 'bg-gray-100' : ''}}"
  (mouseenter)="setSelectedCategoryId()"
  (mouseleave)="removeSelectedCategoryId()"
>
  <div class="flex items-center px-[18px] py-2.5 font-semibold text-sm">
    <a class="flex items-center flex-grow gap-2">
      <img src="icons/{{category.svg}}" alt="{{category.name}}" />
      {{ category.name }}
    </a>
    <button type="button" class="py-1.5">
      <img
        src="{{ isSelected ? 'icons/rowr.svg': 'icons/rowd.svg'}}"
        alt="{{ isSelected ? 'rowd' :'rowr' }}"
        class="w-4 h-4"
      />
    </button>
  </div>
  <div
    class="absolute top-0 z-10 w-full bg-white left-full px-4 py-3 border text-sm *:space-y-2 navbar-item {{isSelected ? 'show' : 'hide'}}"
    *ngIf="Array.isArray(category.subCategories) && category.subCategories.length > 0"
  >
    <ul class="[&amp;>*>a:hover]:text-primary-600">
      <div *ngFor="let subCategory of category.subCategories; last as isLast">
        <app-navbar-sub-item [sub-category]="subCategory" />
        <hr *ngIf="!isLast" />
      </div>
    </ul>
  </div>
</li>

// app/components/shared/NavbarItem/NavbarItem.tsx
import { TCategory } from '~/types';
import './NavbarItem.css';
import { NavbarSubItem } from '~/components/shared/NavbarSubItem';
import { useSelector } from 'react-redux';
import { AppState } from '~/store/config';

type NavbarItemProps = {
  category: TCategory;
  selectedCategoryId: number;
  setSelectedCategoryId: (id: number) => void;
};

export const NavbarItem = (props: NavbarItemProps) => {
  const { category, setSelectedCategoryId, selectedCategoryId } = props;
  const homeSelectedCategoryId = useSelector(
    (state: AppState) => state.home.selectedCategoryId,
  );

  const isSelected =
    category.id === selectedCategoryId ||
    homeSelectedCategoryId === category.id;

  const removeSelectedCategoryId = () => {
    setSelectedCategoryId(0);
  };

  const itemClick = () => {
    console.log('itemClick');
  };

  return (
    <li
      className={isSelected ? 'bg-gray-200' : ''}
      onMouseEnter={() => setSelectedCategoryId(category.id)}
      onMouseLeave={removeSelectedCategoryId}
      onClick={itemClick}
    >
      <div className="flex items-center px-[18px] py-2.5 font-semibold text-sm">
        <a className="flex items-center flex-grow gap-2">
          <img src={`/icons/${category.svg}`} alt={category.name} />
          {category.name}
        </a>
        <button type="button" className="py-1.5">
          <img
            src={isSelected ? '/icons/rowr.svg' : '/icons/rowd.svg'}
            alt={isSelected ? 'rowd' : 'rowr'}
            className="w-4 h-4"
          />
        </button>
      </div>
      {category.subCategories.length > 0 && (
        <div
          className={`absolute top-0 z-10 w-full bg-white left-full px-4 py-3 border text-sm *:space-y-2 navbar-item ${isSelected && 'show'}`}
        >
          <ul className="[&amp;>*>a:hover]:text-primary-600">
            {category.subCategories.map((subCategory) => (
              <div key={subCategory.id}>
                <NavbarSubItem subCategory={subCategory} />
                <hr />
              </div>
            ))}
          </ul>
        </div>
      )}
    </li>
  );
};
